default_language_version:
  python: python3
repos:
  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        args: ["--strict"]
        exclude: '^(docs|tasks|tests)|setup\.py'
        additional_dependencies: ["httpx", "importlib_resources", "packaging", "typer>=0.3.2"]
  - repo: https://gitlab.com/PyCQA/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-bugbear==20.1.4"]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.2
    hooks:
      - id: isort
  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
        args: ["--in-place", "--wrap-summaries=88"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.20.0
    hooks:
      - id: pyupgrade
